apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  selector:
    app: chat # Label to query pods by
  type: NodePort # Important! This will expose a node port over your Kubernetes IP
  ports:
  - protocol: "TCP"
    port: 5000
    # nodePort: 27017 # Port you’ll use to access app through the Kubernetes IP
    # targetPort: 27017