apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo # Label to query pods by
  type: NodePort # Important! This will expose a node port over your Kubernetes IP
  ports:
  - protocol: "TCP"
    port: 27017
    # nodePort: 27017 # Port you’ll use to access app through the Kubernetes IP
    # targetPort: 27017